# Generated by Django 5.1.5 on 2025-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authorCountry',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorPersonId',
            field=models.IntegerField(verbose_name='ID Автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorRegion',
            field=models.CharField(max_length=10, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorSessionId',
            field=models.IntegerField(verbose_name='ID Сессии'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorUserAgent',
            field=models.TextField(verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contentId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Контента'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contentType',
            field=models.CharField(max_length=100, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
