# Generated by Django 5.1.5 on 2025-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_authorcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authorCountry',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorRegion',
            field=models.CharField(max_length=10, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorUserAgent',
            field=models.TextField(null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contentType',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(max_length=10, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
