# Generated by Django 5.1.5 on 2025-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_authorcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contentId',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID Контента'),
        ),
    ]
