# Generated by Django 5.1.5 on 2025-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_authorpersonid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(null=True, verbose_name='URL'),
        ),
    ]
