# Generated by Django 5.1.5 on 2025-01-19 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_article_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('eventType', models.CharField(max_length=100, verbose_name='Тип события')),
                ('sessionId', models.BigIntegerField(verbose_name='ID Сессии')),
                ('contentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article', verbose_name='Статья')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
            },
        ),
    ]
